rr_sync:
  remote_host: <remote-host>
  remote_project_root: <remote-project-root>
  default_project: <project-name>

jira:
  command: <jira-cli-path>
  source_root: <jira-source-root>
  server: <jira-server>

ovhcloud_smoke_tests:
  repository: <smoke-tests-repository>
  rendered_html_root: <rendered-html-root>

cdsv2:
  git_host: <git-host>
  notification_gateway: <notification-gateway>
